### PR TITLE
Feature/add favicon

### LINKED ISSUE #27: Create a favicon for the project
**Is your feature request related to a problem? Please describe.** A clear and
concise description of what the problem is. Ex. I'm always frustrated when [...]

SvelteKit ships with a default favicon.png located at `static/favicon.png`. It's currently the SvelteKit logo. There are no designs for this, but a favicon related to the game of Connect Four would be great to have. Maybe the coin piece, but we leave it up to you to come up with a fun icon.

**Describe the solution you'd like** A clear and concise description of what you
want to happen.

A fun icon representative of the Connect Four game. Dimensions must be 128px x 128px

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

### PR DESCRIPTION
**Pull request by LoganArnett**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update
- [ ] Refactor
- [ ] Optimization

## Description
Adding project Favicon
## Related Tickets & Documents
- Closes #27 

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

### UI accessibility concerns?

_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. For more info, check out the awesome
[Forem Accessibility Docs](https://developers.forem.com/frontend/accessibility)._

## Added/updated tests?

- [ ] Yes
- [X] No, and this is why: This is just a image asset in the static directory
- [ ] I need help with writing tests

## [optional] What gif best describes this PR or how it makes you feel?

alt_text

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
I think this looks great! Thoughts @sadiejay @Narigo?

**Comment by LoganArnett** [comment]
@nickytonline any updates on this?

**Comment by nickytonline** [comment]
> @nickytonline any updates on this?

I'm going to go ahead and approve as it's been a few days. @sadiejay @Narigo, if you want to see some changes to the favicon, we can do that in another pull request.

**Review by nickytonline — APPROVED** [review]
Thanks for this @LoganArnett!

**Pull request merged**
